### ISSUE TITLE
Installation - Implement e2e tests for the installation process on every OS

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1014]
**Context**
Massa Station installation is the one and only entry point, we must cover it by e2e to make sure it's always working. e2e are expensive to build but necessary as manual tests are very often not performed well as the scenarios to cover keep increasing. 

The objective of this issue is to cover the main scenarios described below with e2e on all the [DoD](https://www.notion.so/massa-innoteam/MassaStation-85b1d05ad8df4502af7e1de50d465ae4?pvs=4#39c359bd6da14a12809f4de45c28699b) OS.

**User flow**
List of scenarios to cover: 
1. As a user, I have the previous version of Massa Station installed and I download the new version of Massa Station using the landing page to install it again on my desktop.
2. As a user, I have never installed Massa Station on my desktop, nor any other coding language or software, and I installed Massa Station using the landing page for the 1st time. (ie: no certificate, no port used, nothing)
3. As a user, I am already using port 80 with another software and I try to installed the latest version of Massa Station using the landing page.

**How to**

- [ ] For each OS, cover the scenarios above in the order (from most common to least common)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

This software will return a no-zero exit code if on condition is met:
 - error occurred
 - installation of Massa Station failed
 - https://station.massa not accessible in the browser (can be done later)

- [x] create and register a self hosted github action runner
- [x] runner has virtual box installed with several VMs (on VM for each scenarios)
- [x] runner has a script (detailed bellow)
- [x] binaries and script are copied into the VM by the script
- [ ] (the CI job downloads the installer file, put it into the shared disk) TBC
- [ ] robotgo library to build a go binary that install Massa Station
- [x] the CI job fails if the go software execution failed

script on the runner:
inputs:
- target os
- binary to install (Massa Station release)
- binary robogot (repo [automation](https://github.com/massalabs/automation))
steps:
- select VMs to start based on the input
- start VMs in headless mode
- start screen recorder
- launch the MS installer
- launch robotgo binary that follow the MS installer step (`VBoxManage guestcontrol < uuid | vmname > run`)
- stop video recording, store it
- return status code

Windows scenario to cover:
- win10 with firefox and chrome installed
- above + WSL
- above + acrylic
- same for win11
- ...

Methodology:
- implement from end to end a nominal test case
- add other test cases: browser, OS, initial state of the OS

**QA testing**
As a PM, it is easy to launch (if not automatic) the e2e tests and to understand the results for each of the scenarios above.

**Comment by gregLibert** [comment]
@longgamma-massa, @Thykof For the pre-ico milestone, only a first version with only:
- win11 is expected (must have)
- ideally macos (should have)
- maybe linux (nice to have)
Maybe we should create different issue to follow them.

**Comment by Thykof** [comment]
making use of opencv for go (gocv library) is hard to accomplish (timeboxed 2 days spend). So we will continue with robotgo library only with the us of its keyboard feature. To simplify this, we will run the msiexec is no interaction mode.

**Comment by Thykof** [comment]
We now have an end-to-end automated installation process working: https://github.com/massalabs/automation/actions/runs/5752084781/job/15592252126

**Technical solutions:**
- all the scripts are in the repo automation: https://github.com/massalabs/automation/pull/2
- use windows tasks scheduler to launch the MSI (installer)
- launch the MSI in no-interactive mode
- python3 script on the host machine (runner) to hit keys on the guest VM keyboard to login in into the vbox user on the VM at startup.
- same kind of script confirm the installation of certificate during installation.
- CI checks if the `run.vbs` is present
- on the VM: set “user account control setting” to “never notify” so that there is no admin confirm when MSI launches

**What can be improved?**
- openGL is required on the VM to launch Massa Station (fyne needs it). Experimental features 2D and 3D acceleration on virtualbox are enable but when we install additions guest, the headless mode show black screen freezing.
- no computer vision: the python3 scripts sleep and expect certain popup. Attempt to build robotgo with gocv (opencv for golang) on windows failed after 2 working days. Potential alternative: use opencv for python
- MSI is launches without user interaction: we can run it in normal way and improve the python script.

**How to add test cases?**
The first test case consists of a initial state of the VM: a snapshot that the script in the CI restores.
We can modify the script executed in the CI https://github.com/massalabs/automation/blob/initial-test-scenario/station-installation/test.sh:
- take as first input the name of the VM
- take as second input the uuid or the name of the snapshot to restore

**Comment by Thykof** [comment]
> openGL is required on the VM to launch Massa Station (fyne needs it). Experimental features 2D and 3D acceleration on virtualbox are enable but when we install additions guest, the headless mode show black screen freezing.

Maybe we can activate opengl or 3d acceleration on the OVH server. (cc @qdrn)

**Comment by qdrn** [comment]
> > openGL is required on the VM to launch Massa Station (fyne needs it). Experimental features 2D and 3D acceleration on virtualbox are enable but when we install additions guest, the headless mode show black screen freezing.
> 
> Maybe we can activate opengl or 3d acceleration on the OVH server. (cc @qdrn)

Any blocker for that ?

**Comment by Thykof** [comment]
Waiting for Greg to come back to see if it's possible to active opengl or 3d acceleration on the OVH server. No blocking, we can install Massa Station on the CI but not execute it.

**Comment by Thykof** [comment]
2nd time VMs fill the disk space:
- on the 7th of August so I cleaned all useless snapshots. 
- on the 17 of August, I removed VM win11-ms-installed: it means this test scenario no longer exists.

I don't know why VMs are growing in space, knowing that the last run of the CI is on the 10th of August.

**Comment by Thykof** [comment]
We now have another server with a graphical driver. I transfered win11 VM. We now need to register into Virtual Box, link the CI to that.

**Comment by Thykof** [comment]
On the new server that have a graphical driver, we will:
- configure the Github Action Runner
- check if migrated win11 VM works
- adjust the CI
- add a step to run Massa Station
- wait for cypress e2e test suite and use it: sign an operation

**Comment by Thykof** [comment]
For a MacOs VM see:
- https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-monterey-base
- https://github.com/myspaghetti/macos-virtualbox
