### ISSUE TITLE
Massa Station's legal needs (T&C's and License)

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1020]
**Context**
As any product, Massa Station needs to have T&C's that explain the status of our app,  and the License specifying the lawful usage of the code. 

**User flow
**How to**
- [x]  Implement T&Cs on all OSs-> issue https://github.com/massalabs/station/issues/1156
- [ ] Define the proper License for MS code 
Share these documents with Greg and ask him to discuss details with the legal team
* check this new license used by Uniswap: https://github.com/Uniswap/v4-core/blob/main/LICENSE
* note: you don't have to become a legal expert, these docs are here so Greg (that will make the decision) can have all the info somewhere ;)
- [ ] Add the proper License to repository (and elsewhere, depending on legal requirements)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
See final results via screenshots on each OS to validate that they're well rendered

**Comment by gregLibert** [comment]
@Thykof why do you need technical clarification?

**Comment by Thykof** [comment]
we don't need technical clarification, we need license clarification for this step "Define the proper License for MS code". (I don't know which state is the best for this issue ^^)

**Comment by SlnPons** [comment]
outdated
