### ISSUE TITLE
Blog No code (plug in)

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station#501]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

Allowing non-dev people to create a blog to share interesting content that need to be on the blockchain. For instance, to cover a “Julian Assange case”- like or denounce things anonymously (#metoo, etc…), but not restricted to only such cases. Blog No code can serve as templates or PoC of many information-based on-chain projects.

**Motivations:**

- Enabling a larger audience to use Massa web on-chain functionalities
- Defining tomorrow’s standards by developing a “small-is-beautiful” concept for websites (ie: light websites adapted to the blockchain, you don’t store too heavy framework but stil it’s beautiful)
- Allowing journalist and others to share anonymous information freely

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

1. Come to platform via Thyra plugin page 
2. Install a plugin No-code website builder (or other name)
3. Editor window 
4. Information info like: domain name, and other details if any, with CTA to publish the website
5. Management of already published websites (Nice to have for PoC)

**How to**
*List the step-by-step to get it do if needed - PM*
tbd

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@SebastienValla make sure to add this to Thyra web on-chain (add or make it compatible with). 
In my vision, current web on-chain plugin-to-be only address developer needs. With this issue we could extend it and cover non-dev users. So they must be compatible / integrated together ;)

**Comment by 0xMazout** [comment]
What i understand is the following : 
- [ ] We want a plugin for Thyra. 
- [ ] Generating a zip file ready to upload it on web on chain
- [ ] And have the capability to have dashboards to manage the globality of your websites (so we have a direct link with the web on chain plugin and his capacity to link the websites)
- [ ] Back-office to manage each website
- [ ] This back-office can generate an Home Page with a lists of Articles
- [ ] This back-office can generates Article Pages with a title , pictures , banner image , and a big text , with subtitles to separate Paragraphs
- [ ] When the zip file is generated from the dashboards you can push to the web on chain your file with a name 


Technical Questions : 

- [ ] Do we have capability in the Web On Chain plugin to have routings inside a website ? ex : Go throught homepage then article 1  
- [ ] Do we have easy capability to update frequently a website with the actuals product ? 
- [ ] Did we have a Web on Chain plugin ready to do all of this ? Do we need to update it ?

**Comment by 0xMazout** [comment]
After discussion this morning the solution for the generation of html file is is block-ui : https://blocks-ui.com/

For the POC the perimeter of features are : 

- [ ] Generate the zip file from blocks ui
- [ ] Deploy it in Web On Chain
- [ ] (Not validated) Export as an editable file and re-import it in blocks-ui to update in the future

**Comment by SebastienValla** [comment]
https://github.com/massalabs/thyra-plugin-blogNoCode/pull/1

**Comment by SlnPons** [comment]
Couldn't test this properly. The problem is: I can't install the zip URL using the front-end, there probably is a problem with the zip & release process. 

Here is what I did: 
1. Do a release via github action on the blog no code repo
2. Go run thyra
3. Install the plugin via the zip URL of the release
4. See the following error message


![Image](https://user-images.githubusercontent.com/109611779/227594667-7d20bf8e-d891-4ddf-b893-7095dd721c36.png)


--> I've also notice that there is no arm binary generated in the release. Is it expected?

**Comment by SlnPons** [comment]
alright soooo I can confirm that now the repo is public, the installation works via the front-end

**Comment by SlnPons** [comment]
However, I experiment 2 problems: 
1. When I want to finish the project, I can't see any wallet connected. Even if I've got some 
note: it's connected to thyra wallet so it will be broken soon. fyi - @Thykof (not a problem to break it as this stage!)


![Image](https://user-images.githubusercontent.com/109611779/229109959-de8cf0ce-b560-43e6-805b-d95997f42c90.png)



![Image](https://user-images.githubusercontent.com/109611779/229110009-b2c55753-71a4-4a1f-8ab2-c11dbdd58a11.png)



2. On my terminal, I've got an error

![Image](https://user-images.githubusercontent.com/109611779/229111214-98eacfcb-b3ca-46c6-adce-80bacf2feb73.png)

Can you check @SebastienValla please?

**Comment by Thykof** [comment]
@SlnPons about your second point, I think it's not a problem with the plugin itself, the way we log the output from the plugin is a bit buggy: the prefix is "Error" even when everything is ok.

**Comment by SlnPons** [comment]
Ok thanks @Thykof! It doesn't look like a standard nor normal behaviour..... 
Is it related to thyra plugin manager? or to something else? 
So I can add it to the list of improvement for the mainnet

**Comment by Thykof** [comment]
Maybe @peterjah can help use, I think it's related to thyra plugin manager and to each plugin: the way they output their logs.

**Comment by SlnPons** [comment]
@longgamma-massa can you test and close this ticket if that's ok for you? :)

**Comment by longgamma-massa** [comment]
blocked testing because: a) commands are outdated in the readme, b) plugin needs new manifest to be able to install it in Massastation.
