### ISSUE TITLE
Move new installer to Thyra repository

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#660]
**Context**
New installers has been worked on in the [MassaStation-Installer](https://github.com/massalabs/MassaStation-Installer) repository. Those installers been now nearly ready, we need to be move them in this repository.

**How to**

- [x] Move the installers one by one:
    - [x] #661
    - [x] #665 
    - [x] #666 
- [x] Move and Rework CI to handle versioning correctly https://github.com/massalabs/thyra/issues/675
- [ ] #1066
- [x] Remove `/cmd/thyra-server` https://github.com/massalabs/thyra/pull/732

**Comment by SlnPons** [comment]
Hey @thomas-senechal I think we can close this issue. Can you confirm and close please? :)

**Comment by gregLibert** [comment]
@thomas-senechal is this issue up to date ?

**Comment by thomas-senechal** [comment]
> @thomas-senechal is this issue up to date ?

We still need to move the `CONTRIBUTING.md` to provide some documentation about how the installers work

I think we should open an issue to move and update it, and close this one

**Comment by thomas-senechal** [comment]
Closing since evrything is done except https://github.com/massalabs/station/issues/1066
