### ISSUE TITLE
Update the search page 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#687]
**Context**
Registry page is now rename Search page. It's simpler for end-users.
The objective of this issue is to create the new front-end and connect it to the back-end so the search page is fully functional.

![image](https://github.com/massalabs/thyra/assets/72019005/84fb3c63-65a0-4400-99f3-768c46b69b81)

**User flow**
1. User installs MassaStation 
2. User opens MassaStation home page
3. User clicks on Search Massa blockchain 
4. User sees the search page as design

**Designs**
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=1026-11415&t=PDWu0CLITxbK67Zu-0

**How to**
- [x] #747
- [x] #886
- [x] Check pour les icones: par defaut vs; recup favicon
- [x] Le massa's favorites 
- [x] L'upload du site
 

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow the user flow described

**Comment by SlnPons** [comment]
After testing on the main branch pulled on June 27th at 3pm, I can see this problem: 

- [ ] Account drop down is at 2 different places. Is that normal. It looks weird ....
- [ ] The upload website slider: you can't have a website with 2 characters, why?
- [ ] It is taking a loooooooon time to display the page. Why's that? 
Can we explain these long minutes and identify how to improve this (probably later but this is not really satisfying :/) 

(niceee faviconnn)

**Comment by Thykof** [comment]
> 
>     * [ ]  Account drop down is at 2 different places. Is that normal. It looks weird ....
we reworked this, the dropdown account was temparary left on all page to transform it into network switch

>     * [ ]  The upload website slider: you can't have a website with 2 characters, why?
because the website name must be from 3 to 50 character long.
>     * [ ]  It is taking a loooooooon time to display the page. Why's that?
>       Can we explain these long minutes and identify how to improve this (probably later but this is not really satisfying :/)
it's long because there is no pagination, backend grab all DNS record from the blockchain storage. It will be longer as we add more DNS records (FYI one record is added at each CI execution). I suggestion to show a message saying "gathering website from the blockchain, please wait, this may take a while..."

**Comment by SlnPons** [comment]
Niceee, thanks for all your answers :)
Very clear, for my info what's the delay for a website to be displayed on the page? Or another way to ask is: tous les combien de temps on fait un appel à la blockchain ? (I don't know how to ask this in english...)

Because as a user, when I upload my website, I want to see it a less then 5 sec so I know that it worked. (5 sec is probably too small... but it's web2 standard)

**Comment by Thykof** [comment]
we use a library react query, this library call our API when needed (on page load, on switch windows of your computer...). I think the most painful UX is on page load.

As a user when you upload your website, the app tells you it may take a while, then react query refresh the DNS records and you see your newly uploaded website on the list.

**Comment by B-Naoufal** [comment]
@SlnPons ONLY the fact of each ci add a new website to the DNS increases the latency of fetching websites! Also i agree that we can reduce the wait and render 5 websites , add a pagination and after render the next 5 ..

**Comment by SlnPons** [comment]
Let's not talk about pagination here. As it's plan in another version. 
Can this `I am wondering if we would force this query to happen right after the upload is done so the user can see the page reload + see his/her website.` be done @Thykof? 
Let's discuss this point tomorrow during daily ;)
