### ISSUE TITLE
Update the home page

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#689]
**Context**
Redesign the home page to match the new designs

**User flow**
1. User installs MassaStation 
2. User is redirected to MassaStation home page

**Designs**
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=1026-11415&t=rtJbo6TfzywZSEcI-0

**How to**

- [ ] Update the URL (to be confirmed)
- [ ] Build the new page following the designs 
- [ ] Connect the page to back-end

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow the user flow described.
