### ISSUE TITLE
Fix Store Delete Call and 404 error after deletion

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#910]
**Context**
When there are two plugins installed (and visible in my station section) and the user click son the delete icon, the delete doesn't happen. 
Instead, a get called is made using the useRessource and responding with the my station array of plugin objects. 

&& 

Once the plugin is deleted, a get called is made which returns 404 (maybe because the get call is looking for the deleted plugin) 

**Technical details**
GET 404 after delete :
[Screencast from 28-06-2023 15:49:31.webm](https://github.com/massalabs/station/assets/90157528/33eceb72-1f9c-4c2b-9338-b2de9c93e7f3)

Unsuccessful delete : 
[Screencast from 28-06-2023 15:47:33.webm](https://github.com/massalabs/station/assets/90157528/6e1fbf92-29d6-422e-9079-dc457160a64d)

**Action Plan***

The objective is to move the refetch call to a top level and remove unecessary useEffect & useState hooks

In StationSection.tsx : 

- [x] Add a useEffect that listen to any succesfull operations and changes on plugins (currently installed plugins array), this useEffect will refetch and re-render the Station Section 

In StationPLugin.tsx

- [x] remove the useState, remove the useRessource and associated variables & methods 
- [x] remove the useEffect that listens to isRefetching 

***Update***
After applying these solutions I encountered the following error when installing or deleting a plugin : 
```
useResource.ts:15     GET https://station.massa/plugin-store net::ERR_CONNECTION_CLOSED
```

It seems that there is a conflict between react query and our refetch. But upon some testing, even without the refetch this error appears.

**Comment by SlnPons** [comment]
@pivilartisant is this a bug. What's the expected behaviour here? 
It seems to be transparent for the end-user. Please use existing template to report issue otherwise the prioritisation is too complex as we can't compare things.

**Comment by pivilartisant** [comment]
> @pivilartisant is this a bug. What's the expected behaviour here? It seems to be transparent for the end-user. Please use existing template to report issue otherwise the prioritisation is too complex as we can't compare things.

it seems like it was a bug. Expected behavior is to delete when the delete is clicked. Check here to see the pr fix ! it was nothing big just adding a correct conditional : https://github.com/massalabs/station/pull/911

**Comment by SlnPons** [comment]
@pivilartisant so please update the info about this ticket if the PR exist and in already in CR, so can keep track of it in the board ;)
Thank youu

**Comment by Thykof** [comment]
reopen because the fix is not perfect: https://github.com/massalabs/station/pull/911#discussion_r1246527154

**Comment by SlnPons** [comment]
![Image](https://github.com/massalabs/station/assets/109611779/484df9e0-a917-4365-b84c-0605b00563da)

When I clicked on delete for the node manager plugin, see the error that i've got above. 

After a bit of time, it "works" (see below)


![Image](https://github.com/massalabs/station/assets/109611779/bcaa474f-7f21-4536-8975-ae672629559d)

**Comment by SlnPons** [comment]
Is it expected? I wouldn't expect the error 500 or 404...

**Comment by pivilartisant** [comment]
> Is it expected? I wouldn't expect the error 500 or 404...

No it-s not ! but it's a problem that is known by @Thykof. It seems like we need to do a more in depth investigation & fix

**Comment by Thykof** [comment]
The `404 errors useRessource` you see are generated by https://github.com/massalabs/station/blob/290befdca7a3d464ea1029510ed55922202a7949/web/massastation/src/pages/Store/StationSection/StationPlugin.tsx#L38

The `500 useDelete` is generated either:
- https://github.com/massalabs/station/blob/290befdca7a3d464ea1029510ed55922202a7949/web/massastation/src/pages/Store/StationSection/StationPlugin.tsx#L109
- https://github.com/massalabs/station/blob/290befdca7a3d464ea1029510ed55922202a7949/web/massastation/src/pages/Store/StationSection/StationPlugin.tsx#L134

To fix:
- 404 on useRessource: the is the magic of react-query, we need to rework this page (**frontend**). It's the same as when we fetched the account list when to wallet is installed; here we fetch the plugin detail but the plugin is not found, hence the 404.
- 500 on useDelete: it should not be status code 500 is the plugin is not found: we need a **backend** fix on the endpoint. In addition, same problem as above: we are trying to delete a plugin with an `id` that doesn't exists (this is my hypothesis), because the `id` variable is a react `useState` that is not updated correctly. We also need a **frontend** rework here.

**Comment by pivilartisant** [comment]
> 

I'll focus on this

**Comment by pivilartisant** [comment]
DoR : 

- Time evaluation: 1 day
- Investigation / exploration : find what created a fetch call before the end the delete call + find why the delete call returns 500 after a plugin has been deleted but the UI not updated

**Comment by pivilartisant** [comment]
blocked : 


After applying these solutions I encountered the following error when installing or deleting a plugin :

```
useResource.ts:15     GET https://station.massa/plugin-store net::ERR_CONNECTION_CLOSED
```

It seems that there is a conflict between react query and our refetch. But upon some testing, even without the refetch this error appears.

**Comment by SlnPons** [comment]
@mazmassa could you have a look to see if you can unblocked @pivilartisant  please? 
It seems to be a technical blocker and not a hard stop.

**Comment by pivilartisant** [comment]
> @mazmassa could you have a look to see if you can unblocked @pivilartisant please? It seems to be a technical blocker and not a hard stop.

My question would be the best approach to solving this without introducing potential bugs

**Comment by pivilartisant** [comment]
> > @mazmassa could you have a look to see if you can unblocked @pivilartisant please? It seems to be a technical blocker and not a hard stop.
> 
> We just synced. @pivilartisant has all info he needed. But overall the approach was a good one with the refetch. We just need a refacto for the loading state he will do in a new MR.

see here for PR about fixing the 404

**Comment by SlnPons** [comment]
@pivilartisant I have a problem with this issue. 

When I read the title: "fix delete call and 404 error after deletion"
I expect that: when I delete a plugin on massa station I don't see a 404 error on my console. 

But: I still have it


![Image](https://github.com/massalabs/station/assets/109611779/25944856-8c48-44fe-8896-0d29377838c8)

So AFAIK this issue is not solved.

**Comment by Thykof** [comment]
The good news is that you can delete the plugin! this is fixed, I don't see any 404 about DELETE. The 404 you see are GET http method. It's not visible for the user. It's probably that our code is still not optimal: it performs call to GET /plugin-manager/{id} even after deleting the plugin

**Comment by SlnPons** [comment]
I'm such a bitch sometimes, not even checking the error message --> I KO stuff. 
Thank you @Thykof! and Thanks @pivilartisant & @mazmassa for solving this problem :)
